trigger:
  - master  # Adjust according to your branch

pool:
  vmImage: 'ubuntu-latest'  # Change if needed

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean package'
      publishJUnitResults: true
      jdkVersionOption: '1.17'  # Use the correct JDK version

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'deploy'
      options: '-s $(Build.SourcesDirectory)/.mvn/settings.xml'
      publishJUnitResults: true
      jdkVersionOption: '1.17'  # Use the correct JDK version
