trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: UseJavaVersion@1
    inputs:
      version: '21'
      architecture: 'x64'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.21'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'

  # Copy the JAR/WAR file to the artifact staging directory
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/target'
      Contents: '**/*.jar'  # Change to `**/*.war` if needed
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  # Publish the artifact
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
