# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
on:
  pull_request:
    branches:
      - master

  workflow_dispatch:
    inputs:
      testsPath:
        description: 'Path to Tests to Execute'
        default: 'SignUp.UserManagement'
        type: choice
        options:
          - SignUp.UserManagement
          - ContactWebsiteAdmins.ContactUs

      windowsBrowser:
        description: 'Browser you want to run Windows machine on'
        required: false
        default: 'edge'
        type: choice
        options:
          - edge
          - chrome
      ubuntuBrowser:
        description: 'Browser you want to run Ubuntu machine on'
        required: false
        default: 'edge'
        type: choice
        options:
          - edge
          - chrome

jobs:
  Remote_Tests_Execution_windows:
    runs-on: windows-latest
    env:
      WINDOWS_BROWSER: "edge"
      LAUNCHABLE_TOKEN: ${{ secrets.LAUNCHABLE_TOKEN }}
      LAUNCHABLE_DEBUG: 1
      LAUNCHABLE_REPORT_ERROR: 1

    permissions:
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.6

      - name: Run Tests Contact Us test manually
        continue-on-error: true
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.testsPath == 'ContactWebsiteAdmins.ContactUs'
        run: mvn -DbrowserName="${{github.event.inputs.windowsBrowser}}" -DcontactUsAttachmentPath="$GITHUB_WORKSPACE/" -Dtest="${{github.event.inputs.testsPath}}" test

      - name: Run Tests Signup test manually
        continue-on-error: true
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.testsPath == 'SignUp.UserManagement'
        run: mvn -DbrowserName="${{github.event.inputs.windowsBrowser}}"  -Dtest="${{github.event.inputs.testsPath}}" test

      - name: Generate Allure Report Single File Windows
        continue-on-error: true
        run:  mvn allure:report

      - name: Upload Allure Report as Artifact Windows
        uses: actions/upload-artifact@v3
        with:
          name: Windows_Allure
          path: target/site/allure-maven-plugin/index.html
      - name: Publish Report
        continue-on-error: true
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests Report Windows
          path: 'target/surefire-reports/TEST-*.xml'
          reporter: java-junit
  Remote_Tests_Execution_ubuntu:
    runs-on: ubuntu-latest
    env:
      UBUNTU_BROWSER: "chrome"
      LAUNCHABLE_TOKEN: ${{ secrets.LAUNCHABLE_TOKEN }}
      LAUNCHABLE_DEBUG: 1
      LAUNCHABLE_REPORT_ERROR: 1
    permissions:
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.6

      - name: Run Tests Contact Us test manually
        continue-on-error: true
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.testsPath == 'ContactWebsiteAdmins.ContactUs'
        run: mvn -DbrowserName="${{github.event.inputs.windowsBrowser}}" -DcontactUsAttachmentPath="$GITHUB_WORKSPACE/"  -Dtest="${{github.event.inputs.testsPath}}" test

      - name: Run Tests Signup test manually
        continue-on-error: true
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.testsPath == 'SignUp.UserManagement'
        run: mvn -DbrowserName="${{github.event.inputs.windowsBrowser}}" -Dheadless=headless -Dtest="${{github.event.inputs.testsPath}}" test

      - name: Launchable Record
        uses: launchableinc/record-build-and-test-results-action@v1.0.0
        with:
          build_name: $GITHUB_RUN_ID
          test_runner: maven
          report_path: './**/target/surefire-reports'
        if: always()


      - name: Generate Allure Report Single File Ubuntu
        continue-on-error: true
        run:  mvn allure:report

      - name: Upload Allure Report as Artifact Ubuntu
        uses: actions/upload-artifact@v3
        with:
          name: Ubuntu_Allure
          path: target/site/allure-maven-plugin/index.html

      - name: Generate Surefire Report
        continue-on-error: true
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests Report Ubuntu
          path: 'target/surefire-reports/TEST-*.xml'
          reporter: java-junit
pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
