trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: UseJavaVersion@1
    inputs:
      version: '21'
      architecture: 'x64'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'Path'
      jdkVersionOption: '21'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'

  # Publish the build artifact (JAR/WAR file)
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'  # Destination for artifacts
      artifactName: 'drop'  # Artifact name shown in Azure DevOps
