name: Remote Test Execution

on:
  workflow_dispatch:
    inputs:
      testsPath:
        description: 'Path to Tests to be Executed'
        default: ''
      browser:
        description: 'Browser you want to run on'
        required: true
        default: 'edge'
        type: choice
        options:
          - edge
          - chrome


jobs:
  Remote_Tests_Execution_windows:
    if: ${{ inputs.operatingSystem == 'Windows and Ubuntu' }}
    runs-on: windows-latest
    permissions:
      checks: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.6

      - name: Run Tests
        continue-on-error: true
        run: mvn -DbrowserName="${{github.event.inputs.browser}}" -Dtest="${{github.event.inputs.testsPath}}" test

      - name: Publish Report
        continue-on-error: true
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests Report Edge_Windows
          path: 'target/surefire-reports/TEST-*.xml'
          reporter: java-junit
  Remote_Tests_Execution_ubuntu:
    if: ${{ inputs.operatingSystem == 'Windows and Ubuntu' }}
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.6

      - name: Run Tests
        continue-on-error: true
        run: mvn -DbrowserName="${{github.event.inputs.browser}}" -Dheadless=headless -Dtest="${{github.event.inputs.testsPath}}" test

      - name: Publish Report
        continue-on-error: true
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests Report Edge_Windows
          path: 'target/surefire-reports/TEST-*.xml'
          reporter: java-junit