name: Remote Test Execution

on:
  pull_request:
    branches:
      - master

  workflow_dispatch:
    inputs:
      testsPath:
        description: 'Path to Tests to Execute'
        default: 'SignUp.UserManagement'
        required: false

      windowsBrowser:
        description: 'Browser you want to run Windows machine on'
        required: false
        default: 'edge'
        type: choice
        options:
          - edge
          - chrome
      ubuntuBrowser:
        description: 'Browser you want to run Ubuntu machine on'
        required: false
        default: 'edge'
        type: choice
        options:
          - edge
          - chrome

jobs:
  Remote_Tests_Execution_windows:
    runs-on: windows-latest
    env:
      TESTS_PATH: "SignUp.UserManagement"
      WINDOWS_BROWSER: "edge"
      LAUNCHABLE_TOKEN: ${{ secrets.LAUNCHABLE_TOKEN }}
      LAUNCHABLE_DEBUG: 1
      LAUNCHABLE_REPORT_ERROR: 1

    permissions:
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.6

      - name: Run Tests manually
        continue-on-error: true
        if: github.event_name == 'workflow_dispatch'
        run: mvn -DbrowserName="${{github.event.inputs.windowsBrowser}}" -Dtest="${{github.event.inputs.testsPath}}" test

      - name: Run Tests Automatically
        continue-on-error: true
        if: github.event_name == 'schedule'
        run: mvn -DbrowserName="${{ env.WINDOWS_BROWSER }}" -Dtest="${{ env.TESTS_PATH }}" test

      - name: Record
        uses: launchableinc/record-build-and-test-results-action@v1.0.0
        with:
          build_name: $GITHUB_RUN_ID
          test_runner: <YOUR TEST RUNNER HERE>
          report_path: <PATH TO TEST REPORT XML FILES>
        if: always()

      - name: Generate Allure Report Single File Windows
        continue-on-error: true
        run:  mvn allure:report

      - name: Upload Allure Report as Artifact Windows
        uses: actions/upload-artifact@v3
        with:
          name: Windows_Allure
          path: target/site/allure-maven-plugin/index.html
      - name: Publish Report
        continue-on-error: true
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests Report Windows
          path: 'target/surefire-reports/TEST-*.xml'
          reporter: java-junit
  Remote_Tests_Execution_ubuntu:
    runs-on: ubuntu-latest
    env:
      TESTS_PATH: "SignUp.UserManagement"
      UBUNTU_BROWSER: "chrome"
      LAUNCHABLE_TOKEN: ${{ secrets.LAUNCHABLE_TOKEN }}
      LAUNCHABLE_DEBUG: 1
      LAUNCHABLE_REPORT_ERROR: 1
    permissions:
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.6

      - name: Run Tests manually
        continue-on-error: true
        if: github.event_name == 'workflow_dispatch'
        run: mvn -DbrowserName="${{github.event.inputs.ubuntuBrowser}}" -Dheadless=headless -Dtest="${{github.event.inputs.testsPath}}" test

      - name: Run Tests Automatically
        continue-on-error: true
        if: github.event_name == 'schedule'
        run: mvn -DbrowserName="${{ env.UBUNTU_BROWSER }}" -Dheadless=headless -Dtest="${{ env.TESTS_PATH }}" test

      - name: Launchable Record
        uses: launchableinc/record-build-and-test-results-action@v1.0.0
        with:
          build_name: $GITHUB_RUN_ID
          test_runner: maven
          report_path: './**/target/surefire-reports'
        if: always()


      - name: Generate Allure Report Single File Ubuntu
        continue-on-error: true
        run:  mvn allure:report

      - name: Upload Allure Report as Artifact Ubuntu
        uses: actions/upload-artifact@v3
        with:
          name: Ubuntu_Allure
          path: target/site/allure-maven-plugin/index.html

      - name: Generate Surefire Report
        continue-on-error: true
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests Report Ubuntu
          path: 'target/surefire-reports/TEST-*.xml'
          reporter: java-junit