name: Remote Test Execution

on:
  pull_request:
    branches:
      - master

  workflow_dispatch:
    inputs:
      testsPath:
        description: 'Path to Tests to Execute'
        default: 'SignUp.UserManagement'
      windowsBrowser:
        description: 'Browser you want to run Windows machine on'
        required: true
        default: 'edge'
        type: choice
        options:
          - edge
          - chrome
      ubuntuBrowser:
        description: 'Browser you want to run Ubuntu machine on'
        required: true
        default: 'edge'
        type: choice
        options:
          - edge
          - chrome


jobs:
  Remote_Tests_Execution_windows:
    runs-on: windows-latest
    permissions:
      checks: write
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.6

      - name: Run Tests
        continue-on-error: true
        run: mvn -DbrowserName="${{github.event.inputs.windowsBrowser}}" -Dtest="${{github.event.inputs.testsPath}}" test

      - name: Generate Allure Report Single File Windows
        continue-on-error: true
        run:  mvn allure:report

      - name: Upload Allure Report as Artifact Windows
        uses: actions/upload-artifact@v3
        with:
          name: Windows_Allure
          path: target/site/allure-maven-plugin/index.html
      - name: Publish Report
        continue-on-error: true
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests Report Windows
          path: 'target/surefire-reports/TEST-*.xml'
          reporter: java-junit
  Remote_Tests_Execution_ubuntu:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.6

      - name: Run Tests
        continue-on-error: true
        run: mvn -DbrowserName="${{github.event.inputs.ubuntuBrowser}}" -Dheadless=headless -Dtest="${{github.event.inputs.testsPath}}" test

      - name: Generate Allure Report Single File Ubuntu
        continue-on-error: true
        run:  mvn allure:report

      - name: Upload Allure Report as Artifact Ubuntu
        uses: actions/upload-artifact@v3
        with:
          name: Ubuntu_Allure
          path: target/site/allure-maven-plugin/index.html

      - name: Publish Report
        continue-on-error: true
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests Report Ubuntu
          path: 'target/surefire-reports/TEST-*.xml'
          reporter: java-junit